self.testlib:  [5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 4, 5, 5, 5, 5, 5, 4, 4, 4, 5, 5, 4, 5, 5, 4, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 5, 5, 5, 3, 3, 5, 3, 5, 5, 5, 4, 5, 5, 5, 3, 5, 5, 4, 4, 5, 5, 3, 4]
[32m2021-09-28 20:08:02.588[39m | [1mINFO[22m | [90m/home/av/Desktop/Multi-Agent-Allocation-with-Generative-Network/environment/level_utils.py:75[39m | Tokens in level ['-', 'W', 'X']
Library size increased: 1
x shaoe torch.Size([60, 2450])
Traceback (most recent call last):
  File "main.py", line 188, in <module>
    main()
  File "main.py", line 68, in main
    testc_labeled = classifier.predict(L.test_library)
  File "/home/av/Desktop/Multi-Agent-Allocation-with-Generative-Network/classifier.py", line 110, in predict
    pred = self.forward(X.float())
  File "/home/av/Desktop/Multi-Agent-Allocation-with-Generative-Network/classifier.py", line 53, in forward
    x = self.fc1(x)
  File "/home/av/anaconda3/envs/gpn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/av/anaconda3/envs/gpn/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/av/anaconda3/envs/gpn/lib/python3.7/site-packages/torch/nn/functional.py", line 1674, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [60 x 2450], m2: [200 x 100] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:41