2021-10-07 16:55:54,503 INFO    MainThread:8556 [internal.py:wandb_internal():89] W&B internal server running at pid: 8556, started at: 2021-10-07 16:55:54.502869
2021-10-07 16:55:54,508 DEBUG   HandlerThread:8556 [handler.py:handle_request():126] handle_request: run_start
2021-10-07 16:55:54,510 INFO    WriterThread:8556 [datastore.py:open_for_write():77] open: output/wandb/offline-run-20211007_165553-1falt8oa/run-1falt8oa.wandb
2021-10-07 16:55:56,257 DEBUG   HandlerThread:8556 [meta.py:__init__():40] meta init
2021-10-07 16:55:56,257 DEBUG   HandlerThread:8556 [meta.py:__init__():54] meta init done
2021-10-07 16:55:56,258 DEBUG   HandlerThread:8556 [meta.py:probe():211] probe
2021-10-07 16:55:56,274 DEBUG   HandlerThread:8556 [meta.py:_setup_git():201] setup git
2021-10-07 16:55:56,305 DEBUG   HandlerThread:8556 [meta.py:_setup_git():208] setup git done
2021-10-07 16:55:56,306 DEBUG   HandlerThread:8556 [meta.py:_save_pip():58] save pip
2021-10-07 16:55:56,306 DEBUG   HandlerThread:8556 [meta.py:_save_pip():72] save pip done
2021-10-07 16:55:56,306 DEBUG   HandlerThread:8556 [meta.py:_save_conda():79] save conda
2021-10-07 16:55:57,973 WARNING MainThread:8556 [internal.py:wandb_internal():145] Internal process interrupt: 1
2021-10-07 16:55:58,093 DEBUG   HandlerThread:8556 [meta.py:_save_conda():87] save conda done
2021-10-07 16:55:58,094 DEBUG   HandlerThread:8556 [meta.py:probe():249] probe done
2021-10-07 16:55:58,141 WARNING MainThread:8556 [internal.py:wandb_internal():145] Internal process interrupt: 2
2021-10-07 16:55:58,141 ERROR   MainThread:8556 [internal.py:wandb_internal():148] Internal process interrupted.
2021-10-07 16:55:58,522 INFO    SenderThread:8556 [sender.py:finish():979] shutting down sender
2021-10-07 16:55:59,100 INFO    WriterThread:8556 [datastore.py:close():281] close: output/wandb/offline-run-20211007_165553-1falt8oa/run-1falt8oa.wandb
2021-10-07 16:55:59,102 INFO    MainThread:8556 [internal.py:handle_exit():76] Internal process exited
